### ISSUE TITLE
ModuleNotFoundError: No module named 'markdown'

### ISSUE THREAD

**Issue by mltony** [cartertemm/AI-content-describer#38]
Hello! I'm trying to install content describer for the first time but it throws an exception on startup. Full stack trace:
```
Error importing global plugin AIContentDescriber
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\tmal\AppData\Roaming\nvda\addons\AIContentDescriber\globalPlugins\AIContentDescriber\__init__.py", line 51, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'
Am I doing anything wrong? Is my NVDA too old? Or is there a way to install markdown module into NVDA that I perhaps missed?
Using:
* NVDA Version: 2024.2rc2 (2024.2.0.32502)
* AI Content Describer 2024.05.22

Thanks!

**Comment by mltony** [comment]
I appologize for this, proper upgrade to v2024.4 fixed this.
