### ISSUE TITLE
Error while trying to describe an image

### ISSUE THREAD

**Issue by christopherpross** [cartertemm/AI-content-describer#8]
Hey,
I have NVDA 2023.3 here and when I try to send an image to openai, I get an error from NVDA.
I have setup the apikey and so on correctly. An own writen script verifies that.
Here is the error:

`ERROR - stderr (09:38:13.685) - Thread-683 (21060):
Exception in thread Thread-683:
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "C:\Users\cpross\AppData\Roaming\nvda\addons\AIContentDescriber\globalPlugins\AIContentDescriber\__init__.py", line 215, in describe_image
    ui.message(_("Retrieving description..."))
  File "ui.pyc", line 133, in message
  File "braille.pyc", line 2395, in message
  File "braille.pyc", line 2409, in _resetMessageTimer
  File "wx\core.pyc", line 3451, in __init__
  File "wx\core.pyc", line 3472, in Start
wx._core.wxAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\common\timerimpl.cpp(57) in wxTimerImpl::Start(): timer can only be started from the main thread`
If you need more information, just ask. For me, the addon is not working at this moment.

Thank you for your work.

**Comment by cartertemm** [comment]
Hello @christopherpross,

Are you still facing this issue every time you use the addon?

I'm working on a fairly big update, but if it's more than a one-off I can implement a fix and get it out in the next release. Alas, I think @mzanm's assessment is correct.

**Comment by christopherpross** [comment]
@cartertemm  
Hey,
yeah, the problem persists, I had tried to reinstall the addon and tried also it on an other PC.
If you release a new version, I will give feedback.

**Comment by fcnjd** [comment]
Hey,
I also wnated to say thank you for your work in this. Sadly I have to add: Facing the very same issue, so the addon doesn't work for me either.
NVDA 2023.3 on Win10
